version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - directory: /
    package-ecosystem: npm
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: weekly
