services:
  integration_app:
    build:
      context: ..
      dockerfile: Integration.Dockerfile
    volumes:
      - ../integration:/opt/recruitment-bot/integration
      - ../migrations:/opt/recruitment-bot/migrations
      - ../seeds:/opt/recruitment-bot/seeds
      - ../coverage:/opt/recruitment-bot/coverage
      - ../src:/opt/recruitment-bot/src
      - ../out:/opt/recruitment-bot/out
    env_file:
      - .env
    depends_on:
      - integration_db
  integration_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    tmpfs:
      - /var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
