services:
  # app:
  #   build: .
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - database
  dev_db_pgsql:
    image: postgres:latest
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DATABASE: recruitmentbot
      POSTGRES_USER: recruitmentbot
      POSTGRES_PASSWORD: recruitmentbot
volumes:
  pgsql_data: {}
