services:
  integration_app:
    build: ..
    volumes:
      - ../integration:/opt/huokanbot/integration
      - ../seeds:/opt/huokanbot/seeds
      - ../coverage:/opt/huokanbot/coverage
      - ../src:/opt/huokanbot/src
      - ../out:/opt/huokanbot/out
    env_file:
      - .env
    depends_on:
      - integration_db
  integration_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    tmpfs:
      - /var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
