name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint .
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm test -- -ci
      - name: Build docker images for integration test
        run: docker-compose -f docker/docker-compose-integration-mysql.yml build
      - name: Integration test with mysql
        run: docker-compose -f docker/docker-compose-integration-mysql.yml up --abort-on-container-exit
      - name: Integration test with postgresql
        run: docker-compose -f docker/docker-compose-integration-pgsql.yml up --abort-on-container-exit

  release:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build --tag ghcr.io/oppzippy/recruitment-bot:latest .
      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image
        run: docker push ghcr.io/oppzippy/recruitment-bot:latest
