name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint .
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm test -- -ci

  build:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images for integration test
        run: docker-compose -f docker/docker-compose-integration.yml build
      - name: Integration test
        run: docker-compose -f docker/docker-compose-integration.yml up --abort-on-container-exit
      - name: Build docker image
        run: docker build --tag ghcr.io/oppzippy/huokanbot:latest .
      - name: Log in to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image
        run: docker push ghcr.io/oppzippy/huokanbot:latest
