name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: npm ci
      - name: lint
        run: npx eslint .
      - name: build
        run: npm run build
      - name: unit test
        run: npm test -- -ci
      - name: build docker images
        run: docker-compose -f docker/integration.yml build
      - name: integration test
        run: docker-compose -f docker/integraiton.yml up --abort-on-container-exit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: screen -dm bash -c "./update.sh"
